WIP template bootstrap
claranet/go-zabbix-api pull request #7
Opened 2019-11-08 16:20 UTC by GaetanDepin

2019-11-18 12:50 UTC, GaetanDepin commented
Sorry for the big pr the next one will be shorter
This pr fix existing part and the ci and add support for template, item and trigger

2019-11-19 16:21 UTC, pdecat requested changes
Looks good!

A few remarks here and there.

2019-11-19 16:21 UTC, pdecat commented on README.md
> +Tested on Zabbix 3.2 but should works since 2.0 version.
```suggestion
Tested on Zabbix 3.2 but should work since 2.0 version.
```

2019-11-19 16:21 UTC, pdecat commented on .travis.yml
> +before_install:
Too much is done in the `before_install` phase, could be split between the diverse phases of the travis job lifecycle: https://docs.travis-ci.com/user/job-lifecycle/#the-job-lifecycle

2019-11-19 16:21 UTC, pdecat commented on .travis.yml
> +  - go install github.com/claranet/go-zabbix-api
No go tests are run?

2019-11-19 16:21 UTC, pdecat commented on README.md
> -License: Simplified BSD License (see LICENSE).
This should be preserved too.

2019-11-19 16:21 UTC, pdecat commented on base.go
> +type RowResponse struct {
s/Row/Raw ?

```suggestion
type RawResponse struct {
```

2019-11-19 16:21 UTC, pdecat commented on base.go
> +	req.Header.Add("User-Agent", "github.com/claranet/zabbix")
There should be a method to let terraform override this like in https://github.com/terraform-providers/terraform-provider-kubernetes/blob/v1.10.0/kubernetes/provider.go#L219

2019-11-19 16:21 UTC, pdecat commented on host.go
> +	// Unmonitored unmonitorate host
```suggestion
	// Unmonitored unmonitored host
```

2019-11-19 16:21 UTC, pdecat commented on trigger.go
> +	deleteIds, err := api.TriggersDeleteID(ids)
Why have both `TriggersDeleteByIds()` and `TriggersDeleteID()` functions?

As `TriggersDeleteID()` also accepts a list of ids, it should be named `TriggersDeleteIDs()` if really needed.

2019-11-19 16:21 UTC, pdecat commented on item.go
> +func (api *API) ItemsDeleteID(ids []string) (itemids []interface{}, err error) {
Why have both `ItemsDeleteByIds()` and `ItemsDeleteID()` functions?

As `ItemsDeleteID()` also accepts a list of ids, it should be named `ItemsDeleteIDs()` if really needed.

2019-11-19 16:21 UTC, pdecat commented on macro.go
> +func (api *API) MacroDeleteByID(ids []string) (err error) {
As `MacroDeleteByID()` accepts a list of ids, it should be named `MacroDeleteByIDs()`.

2019-11-19 16:21 UTC, pdecat commented on trigger.go
> +	TriggerParent Hosts `json:"hosts,omitempty"`
This is documented as:
> Return the hosts that the trigger belongs to in the `hosts` property. 

I'd rather stay close to the Zabbix API naming and name this `ParentHosts` (plural).

2019-11-20 12:48 UTC, xp-1000 commented on .travis.yml
> +  - go install github.com/claranet/go-zabbix-api
go test is run automatically by golang plugin of travis (configured at top of this file). You can see it here for example https://travis-ci.org/claranet/go-zabbix-api/builds/614469894?utm_source=github_status&utm_medium=notification

2019-11-20 12:50 UTC, xp-1000 commented on .travis.yml
> +before_install:
totally relevant, I confess I just make the CI works while everything was broken but I can do a little cleaning now thanks

2019-11-20 18:13 UTC, pdecat commented on .travis.yml
> +  - go install github.com/claranet/go-zabbix-api
Oh ok, it's the default script: https://docs.travis-ci.com/user/languages/go/#default-build-script

I'm so used to see this redefined, e.g. https://github.com/terraform-providers/terraform-provider-kubernetes/blob/1.10.0/.travis.yml#L17

2019-11-20 18:16 UTC, pdecat commented on base.go
> +func (api *API) setUserAgent(userAgent string) {
Shouldn't this be exposed?

2019-11-27 18:30 UTC, xp-1000 commented on .travis.yml
> +  - go install github.com/claranet/go-zabbix-api
oh ok I will keep it mind if this causes problems

2019-11-27 19:20 UTC, xp-1000 commented on .travis.yml
> +before_install:
done

2019-12-06 14:23 UTC, pdecat reviewed
A few last remarks to address and we should be good to go! :)

2019-12-06 14:23 UTC, pdecat commented on .travis.yml
>    - 1.6.2
What about using go 1.11+ (1.13 maybe) and switching to go modules?

2019-12-06 14:23 UTC, pdecat commented on README.md
> +Tested on Zabbix 3.2 but should work since 2.0 version.
```suggestion
Tested on Zabbix 3.2, 3.4, 4.0, 4.2 and 4.4, but should work since 2.0 version.
```

2019-12-06 14:23 UTC, pdecat commented on README.md
What about adding a note about https://support.zabbix.com/browse/ZBX-3783 and fixed versions?

2019-12-10 17:56 UTC, xp-1000 commented on README.md
done

2019-12-10 18:54 UTC, xp-1000 commented on .travis.yml
>    - 1.6.2
I added other golang versions https://travis-ci.org/claranet/go-zabbix-api/builds/623315909 but I think switching to go modules could be addressed in future PR. I add a card on trello

2019-12-10 20:53 UTC, pdecat approved these changes
LGTM!

2020-01-23 08:52 UTC, xp-1000 approved these changes
LGTM!

2020-01-23 08:53 UTC, merged