Add_item_type_17/18/19
claranet/go-zabbix-api pull request #9
Opened 2020-04-07 09:56 UTC by david-moreau

2020-04-07 10:04 UTC, pdecat commented on item.go
> +	DEPENDENTItem ItemType = 18
```suggestion
	// DependentItem type
	DependentItem ItemType = 18
```

2020-04-07 10:24 UTC, xp-1000 requested changes
these types should also be added to `item_protoype.go` and `lld_rule.go` resources

2020-04-08 13:39 UTC, pdecat commented on item.go
> +	// SNMPTrap type
```suggestion
	// SNMPTrap type (new in 3.4)
```

2020-04-08 13:40 UTC, pdecat commented on item.go
> +	// DependentItem type
```suggestion
	// DependentItem type (new in 3.4)
```

2020-04-08 13:41 UTC, pdecat commented on item.go
> +	//HTTPAgent type
```suggestion
	//HTTPAgent type (new in 4.0)
```

2022-07-27 13:42 UTC, merged